-- MySQL Script generated by MySQL Workbench
-- 07/18/17 14:27:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema model
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema model
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `model` DEFAULT CHARACTER SET utf8 ;
USE `model` ;

-- -----------------------------------------------------
-- Table `model`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `user` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model`.`UserProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model`.`UserProfile` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firsaname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `userProfile `
    FOREIGN KEY (`idUser`)
    REFERENCES `model`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `model`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `model`;
INSERT INTO `model`.`User` (`idUser`, `username`, `password`) VALUES (1, 'admin', '1111');

COMMIT;

