-- MySQL Script generated by MySQL Workbench
-- Fri Aug 11 13:16:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ShakerWiki
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShakerWiki
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShakerWiki` DEFAULT CHARACTER SET utf8 ;
USE `ShakerWiki` ;

-- -----------------------------------------------------
-- Table `ShakerWiki`.`info_of_cocteils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShakerWiki`.`info_of_cocteils` (
  `idCocteil` INT NOT NULL,
  `name_of_cocteil` VARCHAR(45) NOT NULL,
  `history_of_cocteil` VARCHAR(5000) NOT NULL,
  `like_of_cocteil` INT NULL,
  `cockteils_preparation` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`name_of_cocteil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShakerWiki`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShakerWiki`.`ingredients` (
  `idIngredients` INT NOT NULL AUTO_INCREMENT,
  `ingredient` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`idIngredients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShakerWiki`.`cocteil_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShakerWiki`.`cocteil_ingredients` (
  `name_of_cocteil` VARCHAR(45) NOT NULL,
  `idIngredients` INT NOT NULL,
  `volum` VARCHAR(45) NULL,
  INDEX `fk_cocteil_ingredients_ingredients_idx` (`idIngredients` ASC),
  CONSTRAINT `fk_cocteil_ingredients_ingredients`
    FOREIGN KEY (`idIngredients`)
    REFERENCES `ShakerWiki`.`ingredients` (`idIngredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ShakerWiki`.`info_of_cocteils`
-- -----------------------------------------------------
START TRANSACTION;
USE `ShakerWiki`;
INSERT INTO `ShakerWiki`.`info_of_cocteils` (`idCocteil`, `name_of_cocteil`, `history_of_cocteil`, `like_of_cocteil`, `cockteils_preparation`) VALUES (1, 'Американо', 'Коктейль Американо — это классика алкогольных изысков, родившаяся, благодаря бармену Гаспару Кампари, еще в XIX веке в одном из баров Италии. Он решил смешать биттер на основе цитрусов, красный вермут и содовую, в результате чего получил жгучую алкогольную смесь с привкусом цитрусовой горечи. Такой напиток пришелся по вкусу группе американцев, однажды посетивших бар Кампари. Автору коктейля это очень польстило, и он решил запечатлеть этот приятный для себя момент в названии своего детища — коктейль Американо. Конечно, на протяжении долгого временного пути к XXI столетию рецепт Американо неоднократно дополнялся, изменялся и совершенствовался барменами разных стран, но и сегодня вы можете заказать тот самый Американо, который в свое время пили в баре Гаспара Кампари. Чтобы сохранить всю колоритность напитка, его непременно подадут вам в классическом старомодном бокале, и вы сможете ощутить то же самое, что ощущали ваши предшественники, наслаждавшиеся терпкой горечью творения Кампари. А особые ценители алкогольной горечи могут заказать вариант коктейля с тоником вместо содовой: такой рецепт коктейля Американо был создан специально для создания еще более крепких ощущений.', 0, 'Налить в стакан со льдом кампари и вермут;Аккуратно перемешать ложкой;Долить доверху содовую;Украсить половиной дольки апельсина.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ShakerWiki`.`ingredients`
-- -----------------------------------------------------
START TRANSACTION;
USE `ShakerWiki`;
INSERT INTO `ShakerWiki`.`ingredients` (`idIngredients`, `ingredient`) VALUES (1, 'Апельсин');
INSERT INTO `ShakerWiki`.`ingredients` (`idIngredients`, `ingredient`) VALUES (2, 'Кампари');
INSERT INTO `ShakerWiki`.`ingredients` (`idIngredients`, `ingredient`) VALUES (3, 'Красный вермут');
INSERT INTO `ShakerWiki`.`ingredients` (`idIngredients`, `ingredient`) VALUES (4, 'Содовая');
INSERT INTO `ShakerWiki`.`ingredients` (`idIngredients`, `ingredient`) VALUES (5, 'Лед в кубиках');
INSERT INTO `ShakerWiki`.`ingredients` (`idIngredients`, `ingredient`) VALUES (6, 'Джин');
INSERT INTO `ShakerWiki`.`ingredients` (`idIngredients`, `ingredient`) VALUES (7, 'Абрикосовый бренди');
INSERT INTO `ShakerWiki`.`ingredients` (`idIngredients`, `ingredient`) VALUES (8, 'Апельсиновый сок');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ShakerWiki`.`cocteil_ingredients`
-- -----------------------------------------------------
START TRANSACTION;
USE `ShakerWiki`;
INSERT INTO `ShakerWiki`.`cocteil_ingredients` (`name_of_cocteil`, `idIngredients`, `volum`) VALUES ('Американо', 1, '1/2 дольки');
INSERT INTO `ShakerWiki`.`cocteil_ingredients` (`name_of_cocteil`, `idIngredients`, `volum`) VALUES ('Американо', 2, '30 мл');
INSERT INTO `ShakerWiki`.`cocteil_ingredients` (`name_of_cocteil`, `idIngredients`, `volum`) VALUES ('Американо', 3, '30 мл');
INSERT INTO `ShakerWiki`.`cocteil_ingredients` (`name_of_cocteil`, `idIngredients`, `volum`) VALUES ('Американо', 4, NULL);
INSERT INTO `ShakerWiki`.`cocteil_ingredients` (`name_of_cocteil`, `idIngredients`, `volum`) VALUES ('Американо', 5, NULL);

COMMIT;

