-- MySQL Script generated by MySQL Workbench
-- 07/24/17 14:52:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ShakerWiki
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShakerWiki
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShakerWiki` DEFAULT CHARACTER SET utf8 ;
USE `ShakerWiki` ;

-- -----------------------------------------------------
-- Table `ShakerWiki`.`info_of_cocteils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShakerWiki`.`info_of_cocteils` (
  `idCocteil` INT NOT NULL AUTO_INCREMENT,
  `name_of_cocteil` VARCHAR(45) NOT NULL,
  `history_of_cocteil` VARCHAR(5000) NOT NULL,
  `like_of_cocteil` INT NULL,
  `cockteils_preparation` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idCocteil`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ShakerWiki`.`info_of_cocteils`
-- -----------------------------------------------------
START TRANSACTION;
USE `ShakerWiki`;
INSERT INTO `ShakerWiki`.`info_of_cocteils` (`idCocteil`, `name_of_cocteil`, `history_of_cocteil`, `like_of_cocteil`, `cockteils_preparation`) VALUES (1, 'Американо', 'Коктейль Американо — это классика алкогольных изысков, родившаяся, благодаря бармену Гаспару Кампари, еще в XIX веке в одном из баров Италии. Он решил смешать биттер на основе цитрусов, красный вермут и содовую, в результате чего получил жгучую алкогольную смесь с привкусом цитрусовой горечи. Такой напиток пришелся по вкусу группе американцев, однажды посетивших бар Кампари. Автору коктейля это очень польстило, и он решил запечатлеть этот приятный для себя момент в названии своего детища — коктейль Американо. Конечно, на протяжении долгого временного пути к XXI столетию рецепт Американо неоднократно дополнялся, изменялся и совершенствовался барменами разных стран, но и сегодня вы можете заказать тот самый Американо, который в свое время пили в баре Гаспара Кампари. Чтобы сохранить всю колоритность напитка, его непременно подадут вам в классическом старомодном бокале, и вы сможете ощутить то же самое, что ощущали ваши предшественники, наслаждавшиеся терпкой горечью творения Кампари. А особые ценители алкогольной горечи могут заказать вариант коктейля с тоником вместо содовой: такой рецепт коктейля Американо был создан специально для создания еще более крепких ощущений.', 0, 'Налить в стакан со льдом кампари и вермут;Аккуратно перемешать ложкой;Долить доверху содовую;Украсить половиной дольки апельсина.');

COMMIT;

